# Generated by Django 2.2.5 on 2020-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('nombre', models.CharField(default='', max_length=25, verbose_name='Nombre')),
                ('posicion', models.CharField(choices=[(1, 'Delantero'), (2, 'Centrocampista'), (3, 'Defensa'), (4, 'Portero')], default='', max_length=25, verbose_name='Posición')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('goles', models.IntegerField(verbose_name='Goles')),
                ('tarjetas_amarillas', models.IntegerField(verbose_name='Tarjetas Amarillas')),
                ('tarjetas_rojas', models.IntegerField(verbose_name='Tarjetas rojas')),
                ('equipos', models.CharField(choices=[(1, 'Deportivo Alavés'), (2, 'Athletic Bilbao'), (3, 'Atlético de Madrid'), (4, 'FC Barcelona'), (5, 'RC Celta de Vigo'), (6, 'SD Eibar'), (7, 'RCD Espanyol'), (8, 'Getafe CF'), (9, 'Granada CF'), (10, 'CD Leganés'), (11, 'Levante UD'), (12, 'RCD Mallorca'), (13, 'CA Osasuna'), (14, 'Real Betis Balompié'), (15, 'Real Madrid CF'), (16, 'Real Sociedad'), (17, 'Real Valladolid'), (18, 'Sevilla FC'), (19, 'Valencia CF'), (20, 'Villarreal CF')], default='', max_length=25, verbose_name='Equipo')),
                ('nacionalidad', models.CharField(default='', max_length=25, verbose_name='Nacionalidad')),
                ('partidos_jugados', models.IntegerField(verbose_name='Partidos Jugados')),
                ('idJugador', models.IntegerField(primary_key=True, serialize=False)),
                ('lesionado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('titulo', models.CharField(default='', max_length=25, verbose_name='Título')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('enlace', models.URLField(verbose_name='Enlace a la noticia')),
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(default='', max_length=25, verbose_name='Nombre')),
                ('apellidos', models.CharField(default='', max_length=50, verbose_name='Apellidos')),
                ('usuario', models.CharField(default='', max_length=25, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(default='', max_length=20, verbose_name='Contraseña')),
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
