# Generated by Django 2.2.5 on 2020-01-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
