# Generated by Django 2.2.5 on 2020-01-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200122_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
