# Generated by Django 2.2.5 on 2020-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(default='', max_length=25, verbose_name='Nombre')),
                ('apellidos', models.CharField(default='', max_length=50, verbose_name='Apellidos')),
                ('usuario', models.CharField(default='', max_length=25, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(default='', max_length=20, verbose_name='Contraseña')),
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
